ren "1 *.bat" "%random%.bat"
ren "1 *.bat" "%random%.bat"
ren "1 *.bat" "%random%.bat"
ren "1 *.bat" "%random%.bat"
ren "1 *.bat" "%random%.bat"
ren "1 *.bat" "%random%.bat"
ren "1 *.bat" "%random%.bat"
ren "1 *.bat" "%random%.bat"
